version: '3.9'

services:
  proxy:
    build: reverse-proxy
    ports:
      - 80:80
    depends_on:
      - api
    restart: always

  api:
    build: api
    ports:
      - 8080:8080
    command: yarn start
    restart: always
    volumes:
      - ./api:/src
    deploy:
      resources:
        reservations:
          cpus: 500m
          memory: 1000Mi
        limits:
          cpus: 800m
          memory: 1500Mi
